# Generated by Django 3.1.2 on 2020-11-11 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agregado',
            fields=[
                ('codAgregados', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('codCafe', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('codCargo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('cod_region', models.CharField(max_length=40)),
                ('cod_comuna', models.CharField(default='', max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('rut', models.AutoField(primary_key=True, serialize=False)),
                ('codCargo', models.CharField(max_length=200)),
                ('sueldo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('codFormaPago', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False)),
                ('dv', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=20)),
                ('papellido', models.CharField(max_length=20)),
                ('sapellido', models.CharField(max_length=20)),
                ('contacto', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('contrasena', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Postres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
                ('precio', models.CharField(default='', max_length=20)),
                ('stock', models.CharField(default='', max_length=100)),
                ('img', models.ImageField(default='null', upload_to='fotosPostres')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'postres',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_region', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tamaño',
            fields=[
                ('codTamaño', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_sucursal', models.CharField(max_length=10)),
                ('direccion', models.TextField(default=0)),
                ('cod_comuna', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mantenedor.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaPedido', models.DateField(verbose_name='Fecha de compra')),
                ('descripcion', models.CharField(max_length=100)),
                ('direccion', models.TextField(max_length=200)),
                ('codFormaPago', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='mantenedor.formapago')),
                ('rut', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='mantenedor.persona')),
            ],
        ),
        migrations.CreateModel(
            name='CafeTam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamaño', models.CharField(max_length=50)),
                ('codTamaño', models.CharField(max_length=40)),
                ('codCafe', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='mantenedor.cafe')),
            ],
        ),
    ]
