# Generated by Django 3.1.2 on 2020-11-11 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedor', '0002_catalogo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Catalogo',
        ),
    ]
