# Generated by Django 3.1.2 on 2020-11-11 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedor', '0003_delete_catalogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
                ('imgCatalogo', models.ImageField(default='null', upload_to='fotosPostres')),
            ],
            options={
                'db_table': 'catalogo',
            },
        ),
    ]
