# Generated by Django 3.1.2 on 2020-11-12 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedor', '0005_registrado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrado',
            name='password',
        ),
    ]
