# Generated by Django 3.1.2 on 2020-11-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedor', '0006_remove_registrado_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrado',
            name='clave',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
