# Generated by Django 3.1.2 on 2020-11-19 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedor', '0007_registrado_clave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='contrasena',
        ),
    ]
